services:
  postgres:
    image: debezium/example-postgres:3.0.0.Final
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  pubsub-emulator:
    image: google/cloud-sdk:latest
    command: [gcloud, beta, emulators, pubsub, start, '--host-port=0.0.0.0:8085']
    ports:
      - "8085:8085"
